### ISSUE TITLE
html2text does not support -o option anymore

### ISSUE THREAD

**Issue by yan12125** [keenerd/pkgbuild-watch#2]
As title. Current version cause the following errors:

```
html2text: error: no such option: -o
cp: cannot stat ‘/tmp/tmp.RTSAVfXIDt.txt’: No such file or directory
diff: /tmp/tmp.RTSAVfXIDt.txt: No such file or directory
diff: /home/yen/.urlwatch/cache/cdab56ceddecb80908c3737dba04d7d5da51638a: No such file or directory
cp: cannot stat ‘/tmp/tmp.RTSAVfXIDt.txt’: No such file or directory
Usage: html2text [(filename|url) [encoding]]
```

**Comment by clawoflight** [comment]
This is still an issue. I just commented about it in the AUR.

**Comment by clawoflight** [comment]
I guess the fix would be to replace `-o` in https://github.com/keenerd/pkgbuild-watch/blob/master/urlwatch.sh#L37 with `>`...

**Comment by clawoflight** [comment]
@keenerd Are you still maintaining this?
The fix to this (breaking) error is a simple `s/-o/>/` in that one line.

I would also like to add optional `colordiff` support.
But I don't feel like making a pull request if the last one is over a year old and you never replied to it...

**Comment by yan12125** [comment]
Closing as I haven't used this tool for a long time and it appears dead as mentioned by clawoflight.

BTW, I suggest [nvchecker](https://github.com/lilydjwg/nvchecker/) for others coming here.
